---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: beszel
version: 2.0.0
readme: README.md
authors:
  - Daniel Brennand (github.com/dbrennand)
description: Ansible community collection for Beszel.
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - community
  - beszel
  - linux
  - application
repository: https://github.com/ansible-collections/community.beszel
homepage: https://github.com/ansible-collections/community.beszel
issues: https://github.com/ansible-collections/community.beszel/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - tests/integration
  - tests/unit
  - extensions/molecule
  - changelogs
  - docs
  - collections
  - .github
  - .ansible
  - .tox
  - .venv
  - .agents
  - .claude
  - .vscode
  - .pytest_cache
  - .pre-commit-config.yaml
  - ansible_collections
