[project]
name = "community-beszel"
version = "1.1.0"
description = "Ansible community collection for Beszel."
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "pocketbase",
]

[dependency-groups]
dev = [
    "codespell>=2.4.1",
    "prek>=0.2.20",
    {include-group = "test"},
]
test = [
    "ruff>=0.15.10",
    "ansible-lint>=26.6.0",
    # Introduced via community.general
    "jmespath>=1.0.1",
    "tox-uv-bare>=1.35.1",
    "tox-ansible>=26.3.0",
]

[tool.uv.sources]
tox-ansible = { git = "https://github.com/dbrennand/tox-ansible.git", rev = "cfd3e097abd38f91138462dd9ceb8e6121b4fcd5" }
