[ansible]
skip =
    2.16

[testenv:ruff]
skip_install = true
commands =
    uv run --active ruff format .

[testenv:yamllint]
skip_install = true
commands =
    uv run --active yamllint -c .yamllint .

[testenv:flake8]
skip_install = true
commands =
    uv run --active flake8 --config flake8.ini

[testenv]
commands_pre =
    integration: uv pip install 'molecule' 'molecule-plugins[docker]'
    # Require || true to get past issue:
    # https://github.com/ansible/ansible-dev-environment/issues/349
    # We have a collection dependency for molecule scenarios which needs to be installed prior to running the scenarios
    # This is not handled by tox-ansible natively so we must override the ade command ourselves
    # Installs the dependency and our collection itself in a single command
    integration: bash -c "ade install --requirement extensions/molecule/requirements.yml --no-seed --im none . || true"
    # Do the same as above for unit tests
    # We have a collection dependency for unit tests which needs to be installed prior to running unit tests
    # This is not handled by tox-ansible natively
    unit: bash -c "ade install --requirement tests/unit/requirements.yml --no-seed --im none . || true"
    unit: uv pip install pytest-cov
commands =
    unit: python3 -m pytest --cov --cov-config=.coveragerc --ansible-unit-inject-only ./tests/unit
