---
- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy | Stop and remove agent container
      community.docker.docker_container:
        name: instance
        state: absent
        auto_remove: true

    - name: Destroy | Stop and remove hub container
      community.docker.docker_container:
        name: hub-instance
        state: absent
        auto_remove: true

    - name: Destroy | Stop Beszel Hub Docker Compose Stack
      community.docker.docker_compose_v2:
        project_src: "{{ molecule_scenario_directory }}/.."
        remove_volumes: true
        state: absent
