all:
  children:
    molecule:
      hosts:
        instance:
          ansible_connection: community.docker.docker
    molecule_hub:
      hosts:
        hub-instance:
          ansible_connection: community.docker.docker
